name 'mysql-replication'
maintainer 'Pavel Yudin'
maintainer_email 'pyudin@parallels.com'
license 'apache2'
description 'Installs/Configures mysql-replication'
long_description 'Installs/Configures mysql-replication'
version '0.1.0'
